import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      <body className={inter.className}>
      <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID ?? ""}>
         {children} 
      </GoogleOAuthProvider>
        </body>
    </html>
  
  );
}
